const WORKS_ARCHIVE = [
  {
    id: 'himeji-nazotoki-crossroad',
    title: '姫路なぞ解きクロスロード',
    categories: ['周遊','企業案件'],
    year: 2026,
    month: 3,
    day: 20,
    desc: '姫路で楽しむなぞときクロスロード。',
    hue: 20,
    image: '姫路なぞ解きクロスロード.png',
  },
  {
    id: 'docchi',
    title: 'AnswerはどっちでSHOW!?',
    category: 'イベント',
    year: 2022,
    month: 1,
    day: 14,
    desc: 'どっち謎シリーズ。',
    hue: 15,
    image: 'どっち謎KV（2026広島）.png',
  },
  {
    id: 'dausle',
    title: 'DAUSLE?!',
    category: 'キット',
    year: 2025,
    month: 11,
    day: 8,
    desc: '土産謎第1弾　神戸銘菓ゴーフルをモチーフに作成',
    hue: 0,
    featured: true,
    image: 'DAUSLE?!.jpeg',
  },
  {
    id: 'shingitai',
    title: '心技体',
    category: 'キット',
    year: 2025,
    month: 11,
    day: 8,
    desc: '関西にゆかりのある制作団体が集まって作った謎解きキット',
    hue: 30,
    featured: true,
    image: '心技体.jpeg',
  },
  {
    id: 'aimai',
    title: 'あいまいセツエーション',
    category: '周遊',
    year: 2025,
    month: 7,
    day: 19,
    desc: 'あいまいな状況が連鎖する謎解き周遊イベント。',
    hue: 60,
    featured: true,
    image: 'あいまいセツエーション.png',
  },
  {
    id: 'docchi-r',
    title: 'AnswerはどっちでSHOW!? リターンズ',
    category: 'イベント',
    year: 2025,
    month: 2,
    day: 22,
    desc: 'どっち謎シリーズの関連作品。',
    hue: 45,
    image: 'どっち謎R.jpeg',
  },
  {
    id: 'nazokaruta-ex',
    title: 'ナゾカルタEX',
    category: 'イベント',
    year: 2025,
    month: 5,
    day: 31,
    desc: 'ナゾカルタEX。',
    hue: 90,
    image: 'ナゾカルタEXKV（大阪.png',
  },
  {
    id: 'tokishirazu',
    title: 'トキシラズ',
    category: 'イベント',
    year: 2025,
    month: 7,
    day: 19,
    desc: 'トキシラズの謎解きイベント。',
    hue: 120,
    image: 'トキシラズKV.png',
  },
  {
    id: 'leftover',
    title: 'Leftover',
    category: 'イベント',
    year: 2025,
    month: 7,
    day: 19,
    desc: 'Leftoverの謎解きキット。',
    hue: 270,
    image: 'Leftover.jpeg',
  },
  {
    id: 'kungfuuuu',
    title: 'KungFuuuu',
    category: 'イベント',
    year: 2024,
    month: 9,
    day: 24,
    desc: 'KungFuuuuの謎解きイベント。',
    hue: 150,
    image: 'KungFuuuu\u3000KV.png',
  },
  {
    id: 'wondertale',
    title: 'wondertale',
    category: 'イベント',
    year: 2024,
    month: 2,
    day: 23,
    desc: 'wondertaleの謎解き',
    hue: 240,
    image: 'wondertale.jpeg',
  },
  {
    id: 'mechamore',
    title: 'がけっぷち撮影会 めちゃ盛れ！',
    category: 'イベント',
    year: 2024,
    month: 7,
    day: 6,
    desc: 'めちゃ盛れ！の謎解き',
    hue: 330,
    image: 'A4_MV_MM_240802.png',
  },
  {
    id: 'nazokaruta',
    title: 'ナゾカルタ',
    category: 'イベント',
    year: 2024,
    month: 6,
    day: 2,
    desc: 'ナゾカルタ',
    hue: 345,
    image: 'KV.png',
  },
  {
    id: 'acchisocchitacchi',
    title: 'あっちそっちたっち',
    category: 'イベント',
    year: 2023,
    month: 11,
    day: 11,
    desc: 'あっちそっちたっちの謎解き',
    hue: 180,
    image: 'あっちそっちたっち.jpg',
  },
  {
    id: 'overmap',
    title: 'overmap',
    category: '周遊',
    year: 2023,
    month: 10,
    day: 7,
    desc: 'overmapの謎解き周遊',
    hue: 210,
    image: 'overmap mainviosual.png',
  },
  {
    id: 'hometatae',
    title: 'いこいの場 ホメタタエ',
    category: 'イベント',
    year: 2023,
    month: 10,
    day: 7,
    desc: 'ホメタタエ',
    hue: 300,
    image: 'A4_hometatae_MV.png',
  },
];
