const WORKS_ARCHIVE = [
  {
    id: 'himeji-nazotoki-crossroad',
    title: '姫路なぞ解きクロスロード',
    categories: ['周遊','企業案件'],
    year: 2026,
    month: 3,
    day: 20,
    desc: '姫路で楽しむなぞときクロスロード。',
    hue: 20,
    image: '姫路なぞ解きクロスロード.png',
  },
  {
    id: 'docchi',
    title: 'AnswerはどっちでSHOW!?',
    category: 'イベント',
    year: 2022,
    month: 1,
    day: 14,
    desc: 'どっち謎シリーズ。',
    hue: 15,
    image: 'どっち謎KV（2026広島）.png',
    storyLead: 'あの有名な番組に出演し、華麗に謎を解き『価値なし』を回避せよ！',
    story: [
      '『一流のナゾクラ』を決める裏番組があるらしい…。',
      '普段から謎解きに精通しているあなた達はそんな噂を聞きつけた。',
      '「謎解きがあるのに、参加を逃すわけにはいかない。」',
      'と、あなたたちは興味本位で参加することを決意。',
      '参加してみると例の番組のような、『部屋を選ぶ』謎解きだった。',
      '選択を間違えれば「ランク」が落とされてしまう。',
      'しかも、『価値なし』となった人間たちは行方不明になるという噂も…。',
      '既に、参加を後悔する気持ちも湧いてきたが、迫りくる様々な困難を乗り越えて、この番組を無事にのりこえろ！',
    ],
    overview: {
      team: '1~4人',
      duration: '約55分',
      start: '一斉スタート',
      location: '屋内',
      format: 'ホール型',
    },
  },
  {
    id: 'dausle',
    title: 'DAUSLE?!',
    category: 'キット',
    year: 2025,
    month: 11,
    day: 8,
    desc: '土産謎第1弾　神戸銘菓ゴーフルをモチーフに作成',
    hue: 0,
    featured: true,
    image: 'DAUSLE?!.jpeg',
  },
  {
    id: 'shingitai',
    title: '心技体',
    category: 'キット',
    year: 2025,
    month: 11,
    day: 8,
    desc: '関西にゆかりのある制作団体が集まって作った謎解きキット',
    hue: 30,
    featured: true,
    image: '心技体.jpeg',
  },
  {
    id: 'aimai',
    title: 'あいまいセツエーション',
    category: '周遊',
    year: 2025,
    month: 7,
    day: 19,
    desc: 'あいまいな状況が連鎖する謎解き周遊イベント。',
    hue: 60,
    featured: true,
    image: 'あいまいセツエーション.png',
  },
  {
    id: 'docchi-r',
    title: 'AnswerはどっちでSHOW!? リターンズ',
    category: 'イベント',
    year: 2025,
    month: 2,
    day: 22,
    desc: '「AnswerはどっちでSHOW」の続編がMysteria宝塚で開催！ ShareKOBEによるMysteriaオリジナル謎解き。',
    hue: 45,
    image: 'どっち謎R.jpeg',
    place: 'Mysteria宝塚',
    tagline: '今度の舞台は一軒家',
    storyLead: '例のあの番組がかえってくる！？',
    story: [
      '「AnswerはどっちでSHOW」の続編がMysteria宝塚で開催！',
      '一軒家にある複数の部屋。',
      '時間内に謎を解き、コタエの部屋で正解発表の時を迎えましょう。',
      'あなたは最後まで「一流」の座を死守できるのか！？',
      '（前作とは内容も全て異なります）',
    ],
    overview: {
      team: '2〜4人',
      duration: '約100分',
      start: '時間指定スタート',
      location: '屋内（Mysteria宝塚）',
      format: 'ルーム型',
      note: '3枚ご購入の方は2チームに分かれていただきます。',
    },
    notes: [
      '3人でチケットを購入いただいた場合も、2人・1人に分かれていただきます。',
      '前作「AnswerはどっちでSHOW!?」とは内容がすべて異なります。',
    ],
  },
  {
    id: 'nazokaruta-ex',
    title: 'ナゾカルタEX',
    category: 'イベント',
    year: 2025,
    month: 5,
    day: 31,
    desc: 'ナゾカルタEX。',
    hue: 90,
    image: 'ナゾカルタEXKV（大阪.png',
  },
  {
    id: 'tokishirazu',
    title: 'トキシラズ',
    category: 'イベント',
    year: 2025,
    month: 7,
    day: 19,
    desc: 'トキシラズの謎解きイベント。',
    hue: 120,
    image: 'トキシラズKV.png',
  },
  {
    id: 'leftover',
    title: 'Leftover',
    category: 'イベント',
    year: 2025,
    month: 7,
    day: 19,
    desc: 'Leftoverの謎解きキット。',
    hue: 270,
    image: 'Leftover.jpeg',
  },
  {
    id: 'kungfuuuu',
    title: 'KungFuuuu',
    category: 'イベント',
    year: 2024,
    month: 9,
    day: 24,
    desc: 'KungFuuuuの謎解きイベント。',
    hue: 150,
    image: 'KungFuuuu\u3000KV.png',
  },
  {
    id: 'wondertale',
    title: 'wondertale',
    category: 'イベント',
    year: 2024,
    month: 2,
    day: 23,
    desc: 'wondertaleの謎解き',
    hue: 240,
    image: 'wondertale.jpeg',
  },
  {
    id: 'mechamore',
    title: 'がけっぷち撮影会 めちゃ盛れ！',
    category: 'イベント',
    year: 2024,
    month: 7,
    day: 6,
    desc: 'めちゃ盛れ！の謎解き',
    hue: 330,
    image: 'A4_MV_MM_240802.png',
  },
  {
    id: 'nazokaruta',
    title: 'ナゾカルタ',
    category: 'イベント',
    year: 2024,
    month: 6,
    day: 2,
    desc: 'ナゾカルタ',
    hue: 345,
    image: 'KV.png',
  },
  {
    id: 'acchisocchitacchi',
    title: 'あっちそっちたっち',
    category: 'イベント',
    year: 2023,
    month: 11,
    day: 11,
    desc: 'あっちそっちたっちの謎解き',
    hue: 180,
    image: 'あっちそっちたっち.jpg',
  },
  {
    id: 'overmap',
    title: 'overmap',
    category: '周遊',
    year: 2023,
    month: 10,
    day: 7,
    desc: 'overmapの謎解き周遊',
    hue: 210,
    image: 'overmap mainviosual.png',
  },
  {
    id: 'hometatae',
    title: 'いこいの場 ホメタタエ',
    category: 'イベント',
    year: 2023,
    month: 10,
    day: 7,
    desc: '最近誰かから褒められていますか？ いこいの場ホメタタエへお立ち寄りください。',
    hue: 300,
    image: 'A4_hometatae_MV.png',
    tagline: '最近誰かから褒められていますか？',
    storyLead: '最近誰かから褒められていますか？',
    story: [
      '何かをすればSNSで叩かれる昨今。',
      '他人に褒められるような幸せな場所、それがここ「いこいの場ホメタタエ」です。',
      'どなたであってもご参加可能ですので、ぜひ１度お立ち寄りください！',
      'こんな私でも幸せになれるかなと不安になる必要はありません。',
      '疲れた時、心を癒したい時、いつどんな時でも「いこいの場所ホメタタエ」はあなたをお待ちしております。',
    ],
    overview: {
      team: '1〜4人',
      duration: '約90分',
      start: '一斉スタート',
      location: '屋内',
      format: 'ホール型',
    },
    notes: [
      'ネタバレ禁止公演です。SNSやブログでの公演内容に関する発信はお控えください。',
      '本作品はフィクションです。また、一部尖った表現が含まれる公演となります。',
      '2023年に大阪最宴祭で公演した内容と同一です。',
      'リピート参加の方は「グループチケット」をご購入ください。',
      '体調不良（酩酊等含む）はご参加をお断りする場合がございます。',
      'その他、公演の最初にお伝えする注意事項を遵守ください。',
    ],
  },
];
